export enum AbilityBonus {
  HitPoints = "HitPoints",
  StartingTemporaryHitPoints = "StartingTemporaryHitPoints",
  ActiveDefense = "ActiveDefense",
  PassiveDefense = "PassiveDefense",
  AttackDamage = "AttackDamage",
  GlobalDamage = "GlobalDamage",
  EmpoweredDamage = "EmpoweredDamage",
  DamageResist = "DamageResist",
  CriticalResist = "CriticalResist",
  MissileDefense = "MissileDefense",
  ZoneDefense = "ZoneDefense",
  UnarmedDefense = "UnarmedDefense",
  FortitudeDefense = "FortitudeDefense",
  ReflexDefense = "ReflexDefense",
  MagicDefense = "MagicDefense",
  AdrenalinePoint = "AdrenalinePoint",
  PowerPoint = "PowerPoint",
  RecoveryValue = "RecoveryValue",
  RecoveryPoint = "RecoveryPoint",
  Protector = "Protector",
  TemporaryDamageResist = "TemporaryDamageResist",
  Speed = "Speed",
  Initiative = "Initiative",
  Dualist = "Dualist",
  FindWeakness = "FindWeakness",
  Advance = "Advance",
  WeaponSpell = "WeaponSpell",
  Fortify = "Fortify",
  Healing = "Healing",
  Regeneration = "Regeneration",
  WeaponSpells = "WeaponSpells",
  AttackSpells = "AttackSpells",
  Dodge = "Dodge",
  CriticalStrike = "CriticalStrike",
  Vengence = "Vengence",
  FriendlyMovement = "FriendlyMovement",
  ForcedMovement = "ForcedMovement",
  ToHit = "ToHit",
  NonStacking = "NonStacking",
  HeavyArmorTraining = "HeavyArmorTraining",
  Charging = "Charaging",
  Requires = "Requires",
  Rebuke = "Rebuke",
  Rage = "Rage",
  MissileRangeDistance = "AllRangeDistance",
  ThrownRangeDistance = "ThrownRangeDistance",
  BurstRangeDistance = "BurstRangeDistance",
  SpellRangeDistance = "SpellRangeDistance",
  LineRangeDistance = "LineRangeDistance",
  EvasiveRoll = "EvasiveRoll",
  OpportunityAttack = "OpportunityAttack",
  DifficultTerrain = "DifficultTerrain",
  ToThePain = "ToThePain",
  SummonsHitPoints = "SummonsHitPoints",
  SummonsDamage = "SummonsDamage",
  Thorns = "Thorns",
  Ongoing = "Ongoing",
  Environment = "Environment",
  Concentration = "Concentration",
  SpellLevel = "SpellLevel",
  Overcast = "Overcast",

  /****Action Types****/
  Passive = "Passive",
  Free = "Free",
  Swift = "Swift",
  Minor = "Minor",
  Move = "Move",
  Standard = "Standard",
  Deliberate = "Deliberate",
  Full = "Full",

  /***Spell damage keywords**/
  Heat = "Heat",
  Cold = "Cold",
  Force = "Force",
  Lightning = "Lightning",
  Shadow = "Shadow",
  Poison = "Poison",
  Acid = "Acid",
  Psychic = "Psychic",
  Wild = "Wild",
  Arcane = "Arcane",
  Radiant = "Radiant",

  AdvancedWeaponTraining = "AdvancedWeaponTraining",


  /****Attribute Names***/
  Brawn = "Brawn",
  Vitality = "Vitality",
  Agility = "Agility",
  Quickness = "Quickness",
  Reasoning = "Reasoning",
  Presence = "Presence",
  SelfDiscipline = "SelfDiscipline",
  Intuition = "Intuition",

  /**********Talent Costs********/
  Combat = "Combat",
  Stealth = "Stealth",
  Magic = "Magic",
  General = "General",
  Universal = "Universal",
}
