"use strict";
exports.__esModule = true;
exports.TalentName = void 0;
/**
 * try to keep this in some kind of order like alphabetical to make life easier
 */
var TalentName;
(function (TalentName) {
    TalentName["AccurateCharge"] = "AccurateCharge";
    TalentName["AcceleratedCharge"] = "AcceleratedCharge";
    TalentName["AcceleratedReflexes"] = "AcceleratedReflexes";
    TalentName["AdvancedArmorTraining"] = "AdvancedArmorTraining";
    TalentName["AdvancedWeaponTrainingBigWeapons"] = "AdvancedWeaponTrainingBigWeapons";
    TalentName["AdvancedWeaponTrainingInnerFocus"] = "AdvancedWeaponTrainingInnerFocus";
    TalentName["AdvancedWeaponTrainingRanged"] = "AdvancedWeaponTrainingRanged";
    TalentName["AdvancedWeaponTrainingShieldMastery"] = "AdvancedWeaponTrainingShieldMastery";
    TalentName["AdvancedWeaponTrainingTwoWeaponFighting"] = "AdvancedWeaponTrainingTwoWeaponFighting";
    TalentName["AdvancedWeaponTrainingWaterDancer"] = "AdvancedWeaponTrainingWaterDancer";
    TalentName["ArmorOfTheScoundrel"] = "ArmorOfTheScoundrel";
    TalentName["ArmorOfTheNorthmen"] = "ArmorOfTheNorthmen";
    TalentName["ArmorUp"] = "ArmorUp";
    TalentName["BlindFighting"] = "BlindFighting";
    TalentName["BoilingRage"] = "BoilingRage";
    TalentName["Bolster"] = "Bolster";
    TalentName["BristlingGuardian"] = "BristlingGuardian";
    TalentName["ChargeMastery"] = "ChargeMastery";
    TalentName["ChargeMasteryLesser"] = "ChargeMasteryLesser";
    TalentName["ChiFocus"] = "ChiFocus";
    TalentName["ChiStrikes"] = "ChiStrikes";
    TalentName["CoordinatedStrikes"] = "CoordinatedStrikes";
    TalentName["CommandingStrike"] = "CommandingStrike";
    TalentName["CounterSwing"] = "CounterSwing";
    TalentName["DefensiveCharge"] = "DefensiveCharge";
    TalentName["Deflection"] = "Deflection";
    TalentName["DislodgingBlows"] = "DislodgingBlows";
    TalentName["Enrage"] = "Enrage";
    TalentName["EmpoweredStrikes"] = "EmpoweredStrikes";
    TalentName["FollowUpAttack"] = "FollowUpAttack";
    TalentName["FriendlyController"] = "FriendlyController";
    TalentName["FuriousStrikes"] = "FuriousStrikes";
    TalentName["GracefulStrikes"] = "GracefulStrikes";
    TalentName["GreaterJuggernaut"] = "GreaterJuggernaut";
    TalentName["HealingSpecialization"] = "HealingSpecialization";
    TalentName["ImprovedController"] = "ImprovedController";
    TalentName["ImprovedDefenses"] = "ImprovedDefenses";
    TalentName["ImprovedVitality"] = "ImprovedVitality";
    TalentName["KnightsMove"] = "KnightsMove";
    TalentName["LengthAdvantage"] = "LengthAdvantage";
    TalentName["LethalStrikes"] = "LethalStrikes";
    TalentName["LightningStrike"] = "LightningStrike";
    TalentName["MasterfulStrikes"] = "MasterfulStrikes";
    TalentName["MasterTactician"] = "MasterTactician";
    TalentName["MeasuredCharge"] = "MeasuredCharge";
    TalentName["MeleeArcher"] = "MeleeArcher";
    TalentName["MissileParry"] = "MissileParry";
    TalentName["PowerSource"] = "PowerSource";
    TalentName["PrecisionStrike"] = "PrecisionStrike";
    TalentName["ProtectionMastery"] = "ProtectionMastery";
    TalentName["Reaper"] = "Reaper";
    TalentName["RendingStrikes"] = "RendingStrikes";
    TalentName["SavageCharge"] = "SavageCharge";
    TalentName["ShieldBlock"] = "ShieldBlock";
    TalentName["Sidestep"] = "Sidestep";
    TalentName["Stoicism"] = "Stoicism";
    TalentName["SturdyArm"] = "SturdyArm";
    TalentName["SureShot"] = "SureShot";
    TalentName["Taunt"] = "Taunt";
    TalentName["UnboundFortitude"] = "UnboundFortitude";
    TalentName["Unbreakable"] = "Unbreakable";
    TalentName["UnstoppableMarch"] = "UnstoppableMarch";
    TalentName["VulnerableShots"] = "VulnerableShots";
    TalentName["WeaponMastery"] = "WeaponMastery";
})(TalentName = exports.TalentName || (exports.TalentName = {}));
