/**
 * try to keep this in some kind of order like alphabetical to make life easier
 */
export enum TalentName {
  AccurateCharge = "AccurateCharge",
  AcceleratedCharge = "AcceleratedCharge",
  AcceleratedReflexes = "AcceleratedReflexes",
  AdvancedWeaponTrainingBigWeapons = "AdvancedWeaponTrainingBigWeapons",
  AdvancedWeaponTrainingInnerFocus = "AdvancedWeaponTrainingInnerFocus",
  AdvancedWeaponTrainingRanged = "AdvancedWeaponTrainingRanged",
  AdvancedWeaponTrainingShieldMastery = "AdvancedWeaponTrainingShieldMastery",
  AdvancedWeaponTrainingTwoWeaponFighting = "AdvancedWeaponTrainingTwoWeaponFighting",
  AdvancedWeaponTrainingWaterDancer = "AdvancedWeaponTrainingWaterDancer",
  ArmorUp = "ArmorUp",
  BoilingRage = "BoilingRage",
  Bolster = "Bolster",
  ChargeMastery = "ChargeMastery",
  ChargeMasteryLesser = "ChargeMasteryLesser",
  ChiFocus = "ChiFocus",
  ChiStrikes = "ChiStrikes",
  CoordinatedStrikes = "CoordinatedStrikes",
  CommandingStrike = "CommandingStrike",
  CounterSwing = "CounterSwing",
  DefensiveCharge = "DefensiveCharge",
  Deflection = "Deflection",
  EmpoweredStrikes = "EmpoweredStrikes",
  FollowUpAttack = "FollowUpAttack",
  FriendlyController = "FriendlyController",
  FuriousStrikes = "FuriousStrikes",
  GracefulStrikes = "GracefulStrikes",
  GreaterJuggernaut = "GreaterJuggernaut",
  HealingSpecialization = "HealingSpecialization",
  ImprovedController = "ImprovedController",
  ImprovedDefenses = "ImprovedDefenses",
  ImprovedVitality = "ImprovedVitality",
  KnightsMove = "KnightsMove",
  LengthAdvantage = "LengthAdvantage",
  LethalStrikes = "LethalStrikes",
  LightningStrike = "LightningStrike",
  MasterTactician = "MasterTactician",
  MeasuredCharge = "MeasuredCharge",
  MeleeArcher = "MeleeArcher",
  MissileParry = "MissileParry",
  PowerSource = "PowerSource",
  PrecisionStrike = "PrecisionStrike",
  Reaper = "Reaper",
  RendingStrikes = "RendingStrikes",
  SavageCharge = "SavageCharge",
  ShieldBlock = "ShieldBlock",
  Sidestep = "Sidestep",
  SturdyArm = "SturdyArm",
  SureShot = "SureShot",
  UnstoppableMarch = "UnstoppableMarch",
  VulnerableShots = "VulnerableShots",
}
