/**
 * try to keep this in some kind of order like alphabetical to make life easier
 */
export enum TalentName {
  AccurateCharge = "AccurateCharge",
  AcceleratedCharge = "AcceleratedCharge",
  AcceleratedReflexes = "AcceleratedReflexes",
  AdvancedWeaponTrainingRanged = "AdvancedWeaponTrainingRanged",
  AdvancedWeaponTrainingTwoWeaponFighting = "AdvancedWeaponTrainingTwoWeaponFighting",
  ArmorUp = "ArmorUp",
  BoilingRage = "BoilingRage",
  Bolster = "Bolster",
  ChargeMastery = "ChargeMastery",
  ChargeMasteryLesser = "ChargeMasteryLesser",
  CoordinatedStrikes = "CoordinatedStrikes",
  CommandingStrike = "CommandingStrike",
  CounterSwing = "CounterSwing",
  DefensiveCharge = "DefensiveCharge",
  Deflection = "Deflection",
  EmpoweredStrikes = "EmpoweredStrikes",
  FollowUpAttack = "FollowUpAttack",
  FriendlyController = "FriendlyController",
  FuriousStrikes = "FuriousStrikes",
  GreaterJuggernaut = "GreaterJuggernaut",
  HealingSpecialization = "HealingSpecialization",
  ImprovedController = "ImprovedController",
  ImprovedVitality = "ImprovedVitality",
  KnightsMove = "KnightsMove",
  LethalStrikes = "LethalStrikes",
  LightningStrike = "LightningStrike",
  MasterTactician = "MasterTactician",
  MeasuredCharge = "MeasuredCharge",
  MeleeArcher = "MeleeArcher",
  MissileParry = "MissileParry",
  PowerSource = "PowerSource",
  PrecisionStrike = "PrecisionStrike",
  Reaper = "Reaper",
  SureShot = "SureShot",
  SavageCharge = "SavageCharge",
  UnstoppableMarch = "UnstoppableMarch",
  VulnerableShots = "VulnerableShots"
}
