"use strict";
exports.__esModule = true;
exports.SpellKeywords = void 0;
var SpellKeywords;
(function (SpellKeywords) {
    SpellKeywords["Aura"] = "Aura";
    SpellKeywords["Manipulate"] = "Manipulate";
    SpellKeywords["Thorns"] = "Thorns";
    SpellKeywords["Zone"] = "Zone";
    SpellKeywords["Concentration"] = "Concentration";
    SpellKeywords["Resist"] = "Resist";
    SpellKeywords["Vulnerability"] = "Vulnerability";
    SpellKeywords["Ongoing"] = "Ongoing";
    SpellKeywords["Fortify"] = "Fortify";
    SpellKeywords["Healing"] = "Healing";
    SpellKeywords["Regeneration"] = "Regeneration";
    SpellKeywords["Enhancement"] = "Enhancement";
    SpellKeywords["ForcedMovement"] = "ForcedMovement";
    SpellKeywords["FriendlyMovement"] = "FriendlyMovement";
    SpellKeywords["Dispel"] = "Displet";
    SpellKeywords["Wall"] = "Wall";
    SpellKeywords["Summoning"] = "Summoning";
    SpellKeywords["Weapon"] = "Weapon";
    SpellKeywords["Implement"] = "Implement";
    SpellKeywords["Environment"] = "Environment";
})(SpellKeywords = exports.SpellKeywords || (exports.SpellKeywords = {}));
