export enum Skill {
  Appraisal = "Appraisal",
  Arcana = "Arcana",
  Athletics = "Athletics",
  Balance = "Balance",
  Climbing = "Climbing",
  FirstAid = "FirstAid",
  GatherRumors = "GatherRumors",
  History = "History",
  Leadership = "Leadership",
  SenseMagic = "SenseMagic",
  Nature = "Nature",
  Perception = "Perception",
  Performance = "Performance",
  Persuasion = "Persuasion",
  Religion = "Religion",
  SenseMotive = "SenseMotive",
  StalkingAndHiding = "StalkingAndHiding",
  Swim = "Swim",
  Thievery = "Thievery",
  Tumbling = "Tumbling",
  Warfare = "Warfare"
}
